# Generated by Django 5.0.4 on 2024-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Basic Salary"
                    ),
                ),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="HRA"
                    ),
                ),
                (
                    "special_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Special Allowance",
                    ),
                ),
            ],
        ),
    ]
