# Generated by Django 5.0.4 on 2024-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compensation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="employee_deduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pf_deduction",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF_Deduction"
                    ),
                ),
                (
                    "asic_deduction",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ASIC_Deduction"
                    ),
                ),
            ],
        ),
    ]
