# Generated by Django 5.0.4 on 2024-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compensation", "0002_employee_deduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pf_emp_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="PF (Employers Contribution)",
                    ),
                ),
                (
                    "esic_emp_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="ESIC (Employers Contribution)",
                    ),
                ),
                (
                    "mediclaim",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Mediclaim"
                    ),
                ),
                (
                    "gratuity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gratuity"
                    ),
                ),
            ],
        ),
    ]
