# Generated by Django 5.0.4 on 2024-10-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compensation", "0003_employeecontribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCTC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compensation.employeecontribution",
                        verbose_name="Employer's Contribution",
                    ),
                ),
                (
                    "salary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compensation.employeesalary",
                        verbose_name="Employee Salary",
                    ),
                ),
            ],
        ),
    ]
